spring:
  config:
    import: optional:file:.env[.properties]
  rabbitmq:
    host: ${BACKEND_RABBITMQ_HOST}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    port: ${RABBITMQ_PORT}
  application:
    name: Flash Vagas API
  datasource:
    url: jdbc:postgresql://${BACKEND_DB_HOST}:${BACKEND_DB_HOST_PORT}/${BACKEND_DB_NAME}
    username: ${BACKEND_DB_USERNAME}
    password: ${BACKEND_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
server:
  host: 0.0.0.0
  port: 8080
  error:
    include-stacktrace: never

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

stripe:
  public-key: ${STRIPE_PUBLISHABLE_KEY}
  secret-key: ${STRIPE_SECRET_KEY}
  webhook-secret-key: ${STRIPE_WEBHOOK_SECRET}
  domain: ${DOMAIN}
  customer-portal:
    return-url: ${DOMAIN}/home