version: '3.8'

services:
  backend-db:
    image: postgres:17
    container_name: backend-db
    hostname: backend-db
    ports:
      - ${BACKEND_DB_HOST_PORT}:${BACKEND_DB_CONTAINER_PORT}
    environment:
      POSTGRES_USER: ${BACKEND_DB_USERNAME}
      POSTGRES_PASSWORD: ${BACKEND_DB_PASSWORD}
      POSTGRES_DB: ${BACKEND_DB_NAME}
    volumes:
      - ./data/backend-db:/var/lib/postgresql/data
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:26.1
    container_name: keycloak
    command: start --import-realm
    environment:
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      KC_HOST_NAME: ${KC_HOST_NAME}
      KC_DB: postgres
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: ${KC_DB_NAME}
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD}
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/certs/tls.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/certs/tls.key
    ports:
      - "${KC_HOST_PORT}:${KC_CONTAINER_PORT}"
    volumes:
      - ./docker/keycloak/realms/:/opt/keycloak/data/import/
      - ./docker/keycloak/providers/:/opt/keycloak/providers/
      - ./docker/keycloak/certs/:/opt/keycloak/certs/
    depends_on:
      - keycloak-db
    restart: unless-stopped

  nginx:
    image: nginx:1.25.1
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - gateway-api
      - frontend
      - keycloak
    restart: unless-stopped

  keycloak-db:
    image: postgres:17
    container_name: keycloak-db
    hostname: keycloak-db
    ports:
      - ${KEYCLOAK_DB_HOST_PORT}:${KEYCLOAK_DB_CONTAINER_PORT}
    environment:
      POSTGRES_USER: ${KC_DB_USERNAME}
      POSTGRES_PASSWORD: ${KC_DB_PASSWORD}
      POSTGRES_DB: ${KC_DB_NAME}
    volumes:
      - ./data/keycloak-db:/var/lib/postgresql/data
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - ${RABBITMQ_HOST_PORT}:${RABBITMQ_CONTAINER_PORT}
      - ${RABBITMQ_MANAGEMENT_HOST_PORT}:${RABBITMQ_MANAGEMENT_CONTAINER_PORT}
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
    restart: unless-stopped

  admin-api:
    image: flashvagas/flashvagas:admin-api
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    env_file:
      - ./admin-api/.env.prod
    depends_on:
      - backend-db
      - rabbitmq
      - keycloak
    restart: unless-stopped

  flashvagas-api:
    image: flashvagas/flashvagas:flashvagas-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    env_file:
      - ./flashvagas-api/.env.prod
    depends_on:
      - backend-db
      - rabbitmq
    restart: unless-stopped

  gateway-api:
    image: flashvagas/flashvagas:gateway-api
    ports:
      - "9000:9000"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    env_file:
      - ./gateway-api/.env.prod
    depends_on:
      - flashvagas-api
      - admin-api
    restart: unless-stopped
    
  frontend:
    image: flashvagas/flashvagas:frontend
    ports:
      - "4200:80"
    depends_on:
      - gateway-api
    restart: unless-stopped

networks:
  default:
    name: flashvagas