spring:
  application:
    name: Flashvagas Admin
  config:
    import: optional:file:.env[.properties]
server:
  port: 8081
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

stripe:
  public-key: ${STRIPE_PUBLISHABLE_KEY}
  secret-key: ${STRIPE_SECRET_KEY}
  webhook-secret-key: ${STRIPE_WEBHOOK_SECRET}
  domain: ${DOMAIN}

keycloak:
  token_url: ${KEYCLOAK_TOKEN_URL}
  client_id: ${KEYCLOAK_CLIENT_ID}
  username: ${KEYCLOAK_CLIENT_USERNAME}
  password: ${KEYCLOAK_CLIENT_PASSWORD}
  grant_type: ${KEYCLOAK_CLIENT_GRANT_TYPE}
  host: ${KEYCLOAK_HOST}
  realm: ${KEYCLOAK_REALM}

twilio:
  accountSID: ${TWILIO_ACCOUNT_SID}
  authToken: ${TWILIO_AUTH_TOKEN}
  phoneNumber: ${TWILIO_PHONE_NUMBER}
  messageService: ${TWILIO_MESSAGE_SERVICE}
  templateWithJobsId: ${TWILIO_TEMPLATE_WITH_JOBS}
  templateWithoutJobsId: ${TWILIO_TEMPLATE_WITHOUT_JOBS}

jsearch:
  url: "https://jsearch.p.rapidapi.com/search"
  rapidapi-host: "jsearch.p.rapidapi.com"
  rapidapi-key: ${RAPIDAPI_KEY}
    
plans:
  start:
    jobs:
      quantity: 
        per-message: 5
        per-day: 5
  turbo:
    jobs:
      quantity: 
        per-message: 5
        per-day: 10

job-list-string: 
  base: "https://go.flashvagas.com.br/"

user-preferences:
  url: "http://localhost:9000/api/v1/preferences/user/"

jobs-user:
  url: "http://localhost:9000/api/v1/jobs/user/"

url-shortener:
  url: "http://localhost:8082/"