spring:
  application:
    name: Flashvagas Admin
server:
  port: 8081
springdoc:
  swagger-ui:
    enabled: false
    path: /swagger-ui.html
  api-docs:
    enabled: false
    path: /api-docs

stripe:
  public-key: ${STRIPE_PUBLISHABLE_KEY}
  secret-key: ${STRIPE_SECRET_KEY}
  webhook-secret-key: ${STRIPE_WEBHOOK_SECRET}
  domain: ${DOMAIN}

keycloak:
  token_url: ${KEYCLOAK_TOKEN_URL}
  client_id: ${KEYCLOAK_CLIENT_ID}
  username: ${KEYCLOAK_CLIENT_USERNAME}
  password: ${KEYCLOAK_CLIENT_PASSWORD}
  grant_type: ${KEYCLOAK_CLIENT_GRANT_TYPE}
  host: ${KEYCLOAK_HOST}
  realm: ${KEYCLOAK_REALM}

twilio:
  accountSID: ${TWILIO_ACCOUNT_SID}
  authToken: ${TWILIO_AUTH_TOKEN}
  phoneNumber: ${TWILIO_PHONE_NUMBER}

jsearch:
  url: "https://jsearch.p.rapidapi.com/search"
  rapidapi-host: "jsearch.p.rapidapi.com"
  rapidapi-key: ${RAPIDAPI_KEY}

cloudflare: 
  access:
    client-id: ${CF_ACCESS_CLIENT_ID}
    client-secret: ${CF_ACCESS_CLIENT_SECRET}

plans:
  start:
    jobs:
      quantity: 5
  turbo:
    jobs:
      quantity: 10

user-preferences:
  url: "http://gateway-api:9000/api/v1/preferences/user/"

url-shortener:
  url: "https://go.flashvagas.com.br/"

jobs-user:
  url: "http://gateway-api:9000/api/v1/jobs/user/"